#!/usr/bin/env bash

sudo tee -a /etc/sudoers <<EOT
Defaults !tty_tickets
EOT

podman build --file ./main-container/Containerfile -t build-main
toolbox create -c main --image localhost/build-main

rpm-ostree upgrade
# rpm-ostree override remove plasma-discover plasma-discover-notifier plasma-discover-flatpak

rpm-ostree kargs --append="pci=nocrs" # Fix for my Lenovo Ideapad 3 14IIL05

rpm-ostree install zsh # Install zsh

sudo lchsh # Switch to the z shell
sudo usermod -s /bin/zsh "$USER"
